"""Document parsing and OCR ingestion pipeline.

Extracts text from PDF, DOCX, TXT, and MD files. For PDFs, uses PyMuPDF to
extract text directly; when text extraction yields little content (scanned
PDFs), falls back to OCR (EasyOCR or pytesseract). For DOCX, uses python-docx
to extract paragraphs and tables. TXT/MD files are read directly.

All extracted text is normalised to UTF-8 with paragraph boundaries preserved,
then chunked into semantically coherent segments (512-character windows with
64-character overlap) suitable for embedding. Chinese and English text is
handled properly — CJK characters are never split mid-character.

Public API:
    ingest_file      — parse a single file, return chunk dicts
    ingest_folder    — parse all supported files in a folder
    extract_text     — low-level: extract raw text from a single file
    SUPPORTED_EXTENSIONS — tuple of supported file extensions
"""

from __future__ import annotations

import io
import logging
import os
import uuid
from pathlib import Path
from typing import Any

from rag_kit.embed import chunk_text
from rag_kit.ingest.language import detect_language
from rag_kit.ingest.ocr import is_ocr_available, ocr_image

logger = logging.getLogger(__name__)

SUPPORTED_EXTENSIONS = (".pdf", ".docx", ".xlsx", ".pptx", ".txt", ".md", ".png", ".jpg", ".jpeg", ".tiff", ".tif", ".bmp", ".webp")

# Minimum characters per page to consider text extraction successful.
# If a PDF page yields fewer characters than this, it is treated as a
# scanned/image page and OCR fallback is attempted.
_MIN_TEXT_PER_PAGE = 20


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #


def ingest_file(
    file_path: str | Path,
    chunk_size: int = 512,
    chunk_overlap: int = 64,
    languages: list[str] | None = None,
    use_ocr: bool = True,
    use_vlm: bool = False,
) -> list[dict[str, Any]]:
    """Parse a single file and return a list of chunk dicts.

    Each chunk dict has the shape:
        {
            "id":                 str  — unique chunk identifier,
            "source_file":        str  — file name (not full path),
            "page":               int  — page number (0-indexed, 0 for non-paginated),
            "section":            str  — section heading or "" if none,
            "text":               str  — chunk text (UTF-8, paragraph-aware),
            "language_detected":  str  — "zh", "en", "zh-en", or "unknown",
            "vlm_generated":      bool — True if this chunk was generated by VLM,
            "source_type":        str  — "text" (default) or "image" (VLM caption),
        }

    Args:
        file_path:     Path to the file to ingest.
        chunk_size:    Target chunk length in characters.
        chunk_overlap: Overlap between consecutive chunks in characters.
        languages:     Language codes for OCR (e.g. ["zh", "en"]).
        use_ocr:       Whether to attempt OCR fallback for scanned PDFs.
        use_vlm:       Whether to attempt VLM captioning for image pages.
                       (Requires rag_kit.vlm to be installed.)

    Returns:
        List of chunk dicts. Empty list if the file is unsupported or empty.

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If the file extension is not supported.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    ext = path.suffix.lower()
    if ext not in SUPPORTED_EXTENSIONS:
        raise ValueError(
            f"Unsupported file type '{ext}'. Supported: {SUPPORTED_EXTENSIONS}"
        )

    if languages is None:
        languages = ["zh", "en"]

    source_file = path.name

    # Extract text with page/section metadata.
    pages = _extract_pages(path, ext, languages, use_ocr, use_vlm)

    # Chunk each page and build chunk dicts.
    all_chunks: list[dict[str, Any]] = []

    for page in pages:
        chunks = chunk_text(
            text=page.text,
            source=str(path),
            page=page.page_num,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
        )

        for chunk in chunks:
            lang = detect_language(chunk.text)
            all_chunks.append(
                {
                    "id": chunk.chunk_id,
                    "source": str(path),
                    "source_file": source_file,
                    "page": page.page_num,
                    "section": page.section,
                    "text": chunk.text,
                    "language_detected": lang,
                    "vlm_generated": False,
                    "source_type": "text",
                }
            )

    # VLM: extract and caption visual content (charts, diagrams, images).
    if use_vlm and ext in (".pdf", ".docx"):
        try:
            vlm_chunks = _run_vlm_captioning(str(path), ext, languages)
            for vc in vlm_chunks:
                vc["source_file"] = source_file
                if "id" not in vc:
                    import uuid
                    vc["id"] = uuid.uuid4().hex[:16]
                all_chunks.append(vc)
        except Exception as exc:
            logger.warning("VLM captioning skipped for %s: %s", source_file, exc)

    if not all_chunks:
        logger.warning("No text extracted from %s", path)
        return []

    logger.info(
        "Ingested %s: %d pages, %d chunks (%d VLM)",
        source_file,
        len(pages),
        len(all_chunks),
        sum(1 for c in all_chunks if c.get("vlm_generated")),
    )
    return all_chunks


def _run_vlm_captioning(
    file_path: str,
    ext: str,
    languages: list[str],
) -> list[dict[str, Any]]:
    """Extract visual regions from a document and caption them with VLM.

    Uses rag_kit.vlm.extractor to find images/charts/diagrams, then
    rag_kit.vlm.captioner to generate text descriptions. Each caption
    becomes a chunk with vlm_generated=True and source_type="image".
    """
    from rag_kit.vlm import VLMCaptioner
    from rag_kit.vlm.extractor import extract_images_from_pdf, extract_images_from_docx

    captioner = VLMCaptioner()

    if not captioner.is_available():
        logger.info("VLM model not available, skipping visual captioning")
        return []

    # Determine caption language
    language = "zh" if "zh" in languages else "en"

    regions = []
    if ext == ".pdf":
        import fitz
        doc = fitz.open(file_path)
        try:
            regions = extract_images_from_pdf(doc)
        finally:
            doc.close()
    elif ext == ".docx":
        regions = extract_images_from_docx(file_path)

    if not regions:
        logger.info("No visual regions found in %s", file_path)
        return []

    logger.info("Found %d visual regions in %s", len(regions), file_path)
    return captioner.caption_regions(regions, language=language)


def ingest_folder(
    folder_path: str | Path,
    chunk_size: int = 512,
    chunk_overlap: int = 64,
    languages: list[str] | None = None,
    use_ocr: bool = True,
    use_vlm: bool = False,
) -> list[dict[str, Any]]:
    """Parse all supported files in a folder and return chunk dicts.

    Args:
        folder_path:  Directory to scan for documents.
        chunk_size:    Target chunk length in characters.
        chunk_overlap: Overlap between consecutive chunks.
        languages:     Language codes for OCR.
        use_ocr:       Whether to use OCR fallback for scanned PDFs.
        use_vlm:       Whether to use VLM captioning for image pages.

    Returns:
        List of chunk dicts from all files, concatenated.
    """
    folder = Path(folder_path)
    if not folder.is_dir():
        raise FileNotFoundError(f"Folder not found: {folder}")

    all_chunks: list[dict[str, Any]] = []

    for entry in sorted(folder.rglob("*")):
        if entry.is_file() and entry.suffix.lower() in SUPPORTED_EXTENSIONS:
            try:
                chunks = ingest_file(
                    entry,
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap,
                    languages=languages,
                    use_ocr=use_ocr,
                    use_vlm=use_vlm,
                )
                all_chunks.extend(chunks)
            except Exception as exc:
                logger.error("Failed to ingest %s: %s", entry, exc)

    return all_chunks


def extract_text(
    file_path: str | Path,
    languages: list[str] | None = None,
    use_ocr: bool = True,
) -> list[tuple[int, str]]:
    """Extract raw text from a file, returning (page_number, text) pairs.

    This is the low-level extraction API — no chunking is performed.
    Useful for previewing extracted text before ingestion.

    Args:
        file_path: Path to the file.
        languages: Language codes for OCR.
        use_ocr:   Whether to use OCR fallback.

    Returns:
        List of (page_number, text) tuples. Page numbers are 1-indexed.
        For non-paginated files (TXT, MD), returns a single entry with page=0.
    """
    path = Path(file_path)
    ext = path.suffix.lower()

    if languages is None:
        languages = ["zh", "en"]

    pages = _extract_pages(path, ext, languages, use_ocr, use_vlm=False)
    return [(p.page_num, p.text) for p in pages]


# --------------------------------------------------------------------------- #
# Internal: page-level extraction
# --------------------------------------------------------------------------- #


class _Page:
    """Container for extracted page text and metadata."""

    __slots__ = ("text", "page_num", "section", "extraction_method")

    def __init__(
        self,
        text: str,
        page_num: int = 0,
        section: str = "",
        extraction_method: str = "text",
    ) -> None:
        self.text = text
        self.page_num = page_num
        self.section = section
        self.extraction_method = extraction_method


def _extract_pages(
    path: Path,
    ext: str,
    languages: list[str],
    use_ocr: bool,
    use_vlm: bool,
) -> list[_Page]:
    """Dispatch to the correct extractor based on file extension."""
    if ext == ".pdf":
        return _extract_pdf(path, languages, use_ocr, use_vlm)
    elif ext == ".docx":
        return _extract_docx(path)
    elif ext == ".xlsx":
        return _extract_xlsx(path)
    elif ext == ".pptx":
        return _extract_pptx(path)
    elif ext in (".png", ".jpg", ".jpeg", ".tiff", ".tif", ".bmp", ".webp"):
        return _extract_image(path, languages, use_vlm=use_vlm)
    elif ext in (".txt", ".md"):
        return _extract_text_file(path, ext)
    else:
        logger.warning("Unsupported extension: %s", ext)
        return []


# --------------------------------------------------------------------------- #
# PDF extraction (PyMuPDF + OCR fallback)
# --------------------------------------------------------------------------- #


def _extract_pdf(
    path: Path,
    languages: list[str],
    use_ocr: bool,
    use_vlm: bool,
) -> list[_Page]:
    """Extract text from a PDF using PyMuPDF, with OCR fallback for scanned pages.

    For each page:
    1. Try text extraction via page.get_text().
    2. If the extracted text is too short (< _MIN_TEXT_PER_PAGE chars), the
       page is likely scanned/image-based — fall back to OCR.
    3. If OCR is not available or also fails, try VLM captioning if enabled.
    """
    import fitz  # PyMuPDF

    doc = fitz.open(str(path))
    pages: list[_Page] = []

    try:
        for page_idx in range(len(doc)):
            page = doc[page_idx]
            page_num = page_idx + 1  # 1-indexed

            # Step 1: Try direct text extraction.
            raw_text = page.get_text("text")
            text = _normalize_text(raw_text)

            extraction_method = "text"

            # Step 2: If too little text, try OCR fallback.
            if len(text.strip()) < _MIN_TEXT_PER_PAGE and use_ocr:
                ocr_text = _ocr_pdf_page(page, languages)
                if ocr_text.strip():
                    text = ocr_text
                    extraction_method = "ocr"

            # Step 3: If still empty and VLM is enabled, try captioning.
            if len(text.strip()) < _MIN_TEXT_PER_PAGE and use_vlm:
                vlm_text = _vlm_pdf_page(page, page_num, languages)
                if vlm_text.strip():
                    text = vlm_text
                    extraction_method = "vlm"

            # Determine section heading from the first non-empty line.
            section = _extract_section_heading(text)

            if text.strip():
                pages.append(
                    _Page(
                        text=text,
                        page_num=page_num,
                        section=section,
                        extraction_method=extraction_method,
                    )
                )
    finally:
        doc.close()

    return pages


def _ocr_pdf_page(page: Any, languages: list[str]) -> str:
    """Render a PDF page to an image and run OCR on it."""
    try:
        from PIL import Image

        # Render page at 200 DPI for good OCR quality.
        pix = page.get_pixmap(dpi=200)
        img_data = pix.tobytes("png")
        image = Image.open(io.BytesIO(img_data))

        return ocr_image(image, languages=languages)
    except ImportError:
        logger.debug("OCR not available (easyocr/pytesseract not installed)")
        return ""
    except Exception as exc:
        logger.warning("OCR failed on page: %s", exc)
        return ""


def _vlm_pdf_page(page: Any, page_num: int, languages: list[str]) -> str:
    """Render a PDF page and run VLM captioning (if available)."""
    try:
        from rag_kit.vlm import VLMCaptioner

        pix = page.get_pixmap(dpi=150)
        img_bytes = pix.tobytes("png")

        captioner = VLMCaptioner()
        language = "zh" if "zh" in languages else "en"
        return captioner.caption_image(img_bytes, page_num=page_num, language=language)
    except Exception as exc:
        logger.debug("VLM captioning failed: %s", exc)
        return ""


# --------------------------------------------------------------------------- #
# DOCX extraction (python-docx)
# --------------------------------------------------------------------------- #


def _extract_docx(path: Path) -> list[_Page]:
    """Extract text from a DOCX file using python-docx.

    Extracts paragraphs and table cell text, preserving paragraph boundaries.
    Tables are rendered as tab-separated rows, with rows separated by newlines.
    """
    from docx import Document

    doc = Document(str(path))

    text_parts: list[str] = []
    current_section: str = ""

    # Extract paragraphs.
    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue

        # Detect heading style for section tracking.
        style_name = (para.style.name or "").lower() if para.style else ""
        if "heading" in style_name:
            current_section = text

        text_parts.append(text)

    # Extract tables.
    for table in doc.tables:
        for row in table.rows:
            cells = [cell.text.strip() for cell in row.cells]
            row_text = "\t".join(cells)
            if row_text.strip():
                text_parts.append(row_text)

    full_text = "\n\n".join(text_parts)
    full_text = _normalize_text(full_text)

    if not full_text.strip():
        return []

    return [
        _Page(
            text=full_text,
            page_num=1,  # DOCX is not paginated
            section=current_section,
            extraction_method="text",
        )
    ]


# --------------------------------------------------------------------------- #
# XLSX extraction (openpyxl)
# --------------------------------------------------------------------------- #


def _extract_xlsx(path: Path) -> list[_Page]:
    """Extract text from an .xlsx workbook using openpyxl.

    Every non-empty cell in every non-hidden sheet is extracted as a
    tab-separated row (sheet name, row index, column label).
    """
    try:
        from openpyxl import load_workbook
        from openpyxl.utils import get_column_letter
    except ImportError:
        logger.warning("openpyxl not available — cannot read .xlsx files")
        return []

    parts: list[str] = []
    try:
        wb = load_workbook(str(path), read_only=True, data_only=True)
        try:
            for ws in wb.worksheets:
                if ws.sheet_state in ("hidden", "veryHidden"):
                    continue
                parts.append(f"[Sheet: {ws.title}]")
                for row in ws.iter_rows():
                    cells = []
                    for cell in row:
                        val = cell.value
                        if val is None:
                            continue
                        if isinstance(val, float) and val.is_integer():
                            val = int(val)
                        col = get_column_letter(cell.column)
                        cells.append(f"{col}{cell.row}: {val}")
                    if cells:
                        parts.append(" ".join(cells))
        finally:
            wb.close()
    except Exception as exc:
        logger.warning("Failed to read xlsx %s: %s", path, exc)
        return []

    full_text = _normalize_text("\n".join(parts))
    if not full_text.strip():
        return []
    return [
        _Page(text=full_text, page_num=1, section="", extraction_method="text")
    ]


# --------------------------------------------------------------------------- #
# PPTX extraction (python-pptx)
# --------------------------------------------------------------------------- #


def _extract_pptx(path: Path) -> list[_Page]:
    """Extract text from a .pptx deck using python-pptx.

    Each slide becomes one page (slide number), extracting text from all
    shapes (text frames, tables) and notes where present.
    """
    try:
        from pptx import Presentation
    except ImportError:
        logger.warning("python-pptx not available — cannot read .pptx files")
        return []

    pages: list[_Page] = []
    try:
        prs = Presentation(str(path))
        for idx, slide in enumerate(prs.slides, start=1):
            parts: list[str] = []
            for shape in slide.shapes:
                text = ""
                if shape.has_text_frame:
                    for para in shape.text_frame.paragraphs:
                        t = "".join(run.text for run in para.runs).strip()
                        if t:
                            text += t + "\n"
                elif shape.has_table:
                    for row in shape.table.rows:
                        row_text = "\t".join(cell.text.strip() for cell in row.cells)
                        if row_text.strip():
                            text += row_text + "\n"
                if text.strip():
                    parts.append(text.strip())
            # Slide notes
            if slide.has_notes_slide:
                notes = slide.notes_slide.notes_text_frame.text.strip()
                if notes:
                    parts.append(f"[Notes] {notes}")
            full_text = _normalize_text("\n".join(parts))
            if full_text.strip():
                pages.append(
                    _Page(text=full_text, page_num=idx, section="", extraction_method="text")
                )
    except Exception as exc:
        logger.warning("Failed to read pptx %s: %s", path, exc)
        return []

    return pages


# --------------------------------------------------------------------------- #
# Image extraction (OCR)
# --------------------------------------------------------------------------- #


def _vlm_standalone_image(image: Any, languages: list[str]) -> str:
    """Caption a standalone raster image with the VLM; '' on any failure."""
    try:
        import io

        from PIL import Image as _PILImage

        from rag_kit.vlm import VLMCaptioner

        captioner = VLMCaptioner()
        if not captioner.is_available():
            logger.debug("VLM model not available, skipping standalone image caption")
            return ""
        img = image if isinstance(image, _PILImage.Image) else _PILImage.open(image)
        if img.mode != "RGB":
            img = img.convert("RGB")
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        language = "zh" if "zh" in languages else "en"
        return captioner.caption_image(buf.getvalue(), page_num=0, language=language)
    except Exception as exc:
        logger.debug("VLM standalone image caption failed: %s", exc)
        return ""


def _extract_image(
    path: Path,
    languages: list[str],
    use_vlm: bool = False,
) -> list[_Page]:
    """Extract text from a raster image — OCR, else VLM captioning."""
    try:
        from PIL import Image
    except ImportError:
        return []

    image = Image.open(str(path))
    try:
        img = image.convert("RGB")
    finally:
        image.close()

    text = ocr_image(img, languages=languages)
    if text.strip():
        return [
            _Page(text=_normalize_text(text), page_num=0, section="", extraction_method="ocr")
        ]

    # No OCR-able text (e.g. a pure chart/diagram): fall back to VLM captioning.
    if use_vlm:
        caption = _vlm_standalone_image(img, languages)
        if caption.strip():
            return [
                _Page(
                    text=_normalize_text(caption),
                    page_num=0,
                    section="",
                    extraction_method="vlm",
                )
            ]
    return []


# --------------------------------------------------------------------------- #
# TXT / MD extraction
# --------------------------------------------------------------------------- #


def _extract_text_file(path: Path, ext: str) -> list[_Page]:
    """Extract text from a plain text or Markdown file.

    Reads the file as UTF-8 (with fallback to common encodings), preserving
    paragraph boundaries (double newlines). For Markdown, the raw text is
    kept — heading detection extracts the first heading as the section.
    """
    text = _read_text_file(path)

    if not text.strip():
        return []

    section = ""
    if ext == ".md":
        section = _extract_md_heading(text)

    return [
        _Page(
            text=text,
            page_num=0,  # Non-paginated
            section=section,
            extraction_method="text",
        )
    ]


def _read_text_file(path: Path) -> str:
    """Read a text file, trying UTF-8 first, then common fallback encodings."""
    encodings = ["utf-8", "utf-8-sig", "gbk", "gb2312", "latin-1"]
    for enc in encodings:
        try:
            with open(path, "r", encoding=enc) as f:
                return f.read()
        except (UnicodeDecodeError, LookupError):
            continue
    # Last resort: read bytes and decode with errors="replace".
    logger.warning("Could not decode %s with known encodings; using replacement", path)
    with open(path, "rb") as f:
        return f.read().decode("utf-8", errors="replace")


# --------------------------------------------------------------------------- #
# Text normalisation and helpers
# --------------------------------------------------------------------------- #


def _normalize_text(text: str) -> str:
    """Normalize text to clean UTF-8.

    - Strips excessive blank lines (more than 2 consecutive newlines → 2).
    - Normalizes different line endings to \\n.
    - Strips trailing whitespace on each line.
    - Preserves paragraph boundaries (double newlines).
    - Does NOT strip or modify CJK characters.
    """
    if not text:
        return ""

    # Normalize line endings.
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Strip trailing whitespace on each line.
    lines = [line.rstrip() for line in text.split("\n")]
    text = "\n".join(lines)

    # Collapse 3+ consecutive newlines to 2 (paragraph boundary).
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")

    # Strip leading/trailing whitespace.
    return text.strip()


def _extract_section_heading(text: str) -> str:
    """Extract a section heading from the first few lines of text.

    Looks for the first non-empty line that is short (< 100 chars) and
    does not end with sentence-ending punctuation.
    """
    if not text:
        return ""

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if len(line) < 100 and not line.endswith((".", "。", "!", "！", "?", "？")):
            return line
        break  # Only check the first non-empty line.

    return ""


def _extract_md_heading(text: str) -> str:
    """Extract the first Markdown heading from text."""
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            # Remove # prefixes and return the heading text.
            return stripped.lstrip("#").strip()
    return ""
